Updated task list to use ol rather than manually entered h2
thepensionsregulator/govuk-frontend-aspnetcore-extensions pull request #180
Opened 2023-07-24 09:58 UTC by bentpr

Updated following accessibility feedback.

New structure is:

```html
<govuk-tasklist>
    <govuk-task-list-section>
        <govuk-task-list-section-name>Section Name</govuk-task-list-section-name>
        <govuk-task-list-task href="#">
            <govuk-task-list-task-name>Yet <i>another</i> thing to do</govuk-task-list-task-name>
            <govuk-task-list-task-hint>This thing has an <strong>important deadline</strong> you need to know about.</govuk-task-list-task-hint>
            <govuk-task-list-task-status status="Completed" />
        </govuk-task-list-task>
    </govuk-task-list-section>
</govuk-tasklist>
```

Umbraco project updated - Task List now requires Task List Section, and each Task List Section will require a collection of Task List Items underneath.

Html Generated is of the form:

```html
<ol class="govuk-task-list">
   <li>
      <h2 class="govuk-task-list__section">
      <span class="govuk-task-list__section-number">1. </span>Complete this first</h2>
      <ul class="govuk-task-list__items">
            <li class="govuk-task-list__item " id="someid">
            ...
            </li>
      </ul>
   </li>
</ol>
```

2023-07-24 16:04 UTC, sussexrick requested changes
I think you're working to some incorrect assumptions here.

The evidence we've got for the emerging GOV.UK standard:

- the [current published Task list pages pattern](https://design-system.service.gov.uk/patterns/task-list-pages/), which is from before development as a component began - no HTML given
- the [current draft of the Task list pages pattern](https://deploy-preview-1994--govuk-design-system-preview.netlify.app/patterns/task-list-pages/), which is the most recent and uses `h2.govuk-heading-m` with no ordered list, but is not finalised
- the [GOV.UK prototype kit example](https://prototype-kit.service.gov.uk/v12/docs/templates/task-list) which both of the above link to. It uses ordered lists and its own h2 class, but with `app-` prefixes that indicate those styles are part of that application and not the GOV.UK design system. This is at least as old as the current published pattern, and carries a message saying it's obsolete, but the new version of the GOV.UK prototype kit doesn't provide an updated example.

So what is the evidence that we need this change at all? We already support the HTML specified in the most recent documentation we have. 

Your terminology is also not consistent with the GOV.UK Task list page pattern. If you read either version of that page a 'task list' is a simple list of tasks, which may then be placed in a 'group'. The 'task list' is not the set of 'groups' as you have it, it is the set of tasks within a 'group'. And the 'group' is what you've called a 'section'.

I can see you've taken your terminology from the GOV.UK prototype kit example, but I'm not convinced that's either up-to-date or definitive. I've posted a message on the cross-gov Slack channel to try to find out what the guidance is, but the most likely person to know is on holiday.

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/DataTypes/GOVUKTaskListSectionsBlockList.config
> +<DataType Key="087d7045-6e55-46da-9274-c0a946d4c671" Alias="GOV,UK Task List Sections Block List" Level="1">
typo in the name

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/DataTypes/GOVUKTaskListSectionsBlockList.config
> +      "label": "{{itemKey}} (Task list section)",
`itemKey` is not a property on this data type. Should be `sectionName`.

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/ContentTypes/govuktasklistsection.config
> +    <Icon>icon-check color-black</Icon>
It would be nicer to have a unique icon - I'd suggest `icon-map` looks a bit like the task list was opened~

![image](https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/assets/1260550/96211bb3-92ce-4eb4-b1b5-ead6e8f4d15f)

Opens to:
![image](https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/assets/1260550/8e394698-f6a3-4606-9a80-a59d3e71f853)

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/ContentTypes/govuktasklistsection.config
> +      <Name>Section Name</Name>
Property display names should be Sentence case

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/ContentTypes/govuktasklistsection.config
This should have a matching settings type which uses the 'CSS classes' composition, and any CSS classes entered on the settings should be applied to the outermost HTML element, which in this case would be the `li` for the section. This would then be consistent with all the other components.

2023-07-24 16:04 UTC, sussexrick commented on lib/govuk-frontend
This shouldn't be here. I suspect you need to run `git submodule --update`.

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/DataTypes/TaskListSection.config
Needs a uSync > Everything > Clean export to get rid of files like this

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/Languages/en-us.config
We don't want US English back again

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/ContentTypes/govuktasklist.config
Content types and data types need to be copied to GovUk.Frontend.Umbraco with the same build action as all the rest. The result is they would not be included in the NuGet package, and old versions would overwrite the ones here in this example application. This happened for me and I had to work out why your changes were not importing.

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/Styles/_tpr-task-list.scss
> +.govuk-task-list__section {
Code that is meant to affect the design for plain GOV.UK should be in _govuk-task-list.scss. At the moment the GOV.UK design is not aligned with the numbers, which I think was your intention with the TPR style:

<img width="508" alt="image" src="https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/assets/1260550/848261eb-eb1d-4e42-982b-0eb891750966">

You can't assume numbers and indenting are required. The [latest draft of GOV.UK guidance](https://deploy-preview-1994--govuk-design-system-preview.netlify.app/patterns/task-list-pages/) doesn't have them, and neither does existing usage within TPR:

<img width="502" alt="image" src="https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/assets/1260550/a6e471cc-b5fb-4ae4-bf58-b97c81121e07">

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/HtmlGeneration/ComponentGenerator.TaskList.cs
> +                sectionNumberBuilder.MergeCssClass("govuk-task-list__section-number");
You can't assume numbers are required. The [latest draft of GOV.UK guidance](https://deploy-preview-1994--govuk-design-system-preview.netlify.app/patterns/task-list-pages/) doesn't have them, and neither does existing usage within TPR:

<img width="502" alt="image" src="https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/assets/1260550/a6e471cc-b5fb-4ae4-bf58-b97c81121e07">

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/ContentTypes/govuktasklist.config
> +      <MandatoryMessage>You must supply at least one section</MandatoryMessage>
Why is there a minimum here but not for tasks within a section? It's actually useful to have no minimum, even though you always expect one to be added on a finished page, so that you can save a page in a partially-completed state.

2023-07-24 16:04 UTC, sussexrick commented on GovUk.Frontend.Umbraco.ExampleApp/uSync/v9/Content/task-list.config
> +      "sections": "{\r\n  \"layout\": {\r\n    \"Umbraco.BlockGrid\": [\r\n      {\r\n        \"contentUdi\": \"umb://element/9ac18ea1eb064f74933ca2f4bd1bb65f\",\r\n        \"areas\": [],\r\n
The old version of the page had a lot more variations of tasks - all the possible statuses, hints, no hints, formatted hints, statuses set in code and in the back office. This was deliberate, to have a test of all the different functionality. We don't want to lose that.

![image](https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/assets/1260550/d1406a9a-2ed7-4ea5-be6f-bcd79d9fe6c5)

2023-07-26 09:32 UTC, bentpr commented
> I think you're working to some incorrect assumptions here.
> 
> The evidence we've got for the emerging GOV.UK standard:
> 
> * the [current published Task list pages pattern](https://design-system.service.gov.uk/patterns/task-list-pages/), which is from before development as a component began - no HTML given
> * the [current draft of the Task list pages pattern](https://deploy-preview-1994--govuk-design-system-preview.netlify.app/patterns/task-list-pages/), which is the most recent and uses `h2.govuk-heading-m` with no ordered list, but is not finalised
> * the [GOV.UK prototype kit example](https://prototype-kit.service.gov.uk/v12/docs/templates/task-list) which both of the above link to. It uses ordered lists and its own h2 class, but with `app-` prefixes that indicate those styles are part of that application and not the GOV.UK design system. This is at least as old as the current published pattern, and carries a message saying it's obsolete, but the new version of the GOV.UK prototype kit doesn't provide an updated example.
> 
> So what is the evidence that we need this change at all? We already support the HTML specified in the most recent documentation we have. You refer to accessibility feedback but not what the feedback was. We should perhaps be feeding that into the development of `govuk-frontend` if it's valid.
> 
> Your terminology is also not consistent with the GOV.UK Task list page pattern. If you read either version of that page a 'task list' is a simple list of tasks, which may then be placed in a 'group'. The 'task list' is not the set of 'groups' as you have it, it is the set of tasks within a 'group'. And the 'group' is what you've called a 'section'.
> 
> I can see you've taken your terminology from the GOV.UK prototype kit example, but I'm not convinced that's either up-to-date or definitive. I've posted a message on the cross-gov Slack channel to try to find out what the guidance is, but the most likely person to know is on holiday.

This was our accessibility feedback:

![image](https://github.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/assets/62099029/4bcc07c5-91a9-41c9-a789-b39ab0196212)

Maybe then we have two options - one for numeric/ol, and one just for an auto-generated h2? That way, both options are there

2023-07-27 13:48 UTC, closed without merging