Create overridable block grid types and add support to testing project
thepensionsregulator/govuk-frontend-aspnetcore-extensions pull request #221
Opened 2023-10-02 14:42 UTC by sussexrick

- Create overridable block grid classes following the same pattern as the existing classes for block lists. 
- Add tests, including new tests for the existing block list classes.
- Adds support for block grids to the Umbraco testing package, similar to that which already exists for block lists.

2023-10-03 08:03 UTC, HarryAmmon requested changes

2023-10-03 08:03 UTC, HarryAmmon commented on ThePensionsRegulator.Umbraco.Tests/Blocks/OverridableBlockGridModelTests.cs
> +        }
What about the grandchild?

2023-10-03 08:10 UTC, ancientyouthman submitted a review, later dismissed

2023-10-09 09:16 UTC, sussexrick commented on ThePensionsRegulator.Umbraco.Tests/Blocks/OverridableBlockGridModelTests.cs
> +        }
Extra test added for both block list and block grid types.

2023-10-09 12:19 UTC, HarryAmmon approved these changes

2023-10-09 12:22 UTC, merged