Add the ability to hide the day field for a Date input in Umbraco
thepensionsregulator/govuk-frontend-aspnetcore-extensions pull request #249
Opened 2023-11-30 18:00 UTC by sussexrick

[AB#173233](https://dev.azure.com/thepensionsregulator/0158f35d-cea5-4d9d-adc8-9fc3d3d98793/_workitems/edit/173233) requires a 'Date input' component that only asks for the month and year. This PR makes that an option in Umbraco.

![Month and year only](https://raw.githubusercontent.com/thepensionsregulator/govuk-frontend-aspnetcore-extensions/553bb3d671d9ae2ac9590ba823600a29c05aaff3/docs/images/date-input-month-year.png)

It is a follow-up to #246 to avoid an inevitable merge conflict from that one, so it should not be merged until that one has already been completed. The code can be reviewed now by looking at the relevant commit.

The base `<govuk-date-input />` component that we use does not support this option, so we need to use the approach we took for adding validation attributes. This involves creating a tag helper that wraps the original component, reads the HTML output by that component, and updates that HTML using `HtmlAgilityPack`.

The `UmbracoDateInputModelBinder` is updated to know when it should not expect a day field, and in that case it uses 1 for the day so that a `DateTime` or `DateOnly` object can be created. This is why this change is for Umbraco projects only - the `DateInputModelBinder` in the base project doesn't do this, and always expects a day.

The backoffice preview reflects the selection made. 

The Umbraco example app has an example of a month and year date field.

2023-12-01 15:43 UTC, HarryAmmon requested changes

2023-12-01 15:43 UTC, HarryAmmon commented on GovUk.Frontend.Umbraco.ExampleApp/Models/ModelsBuilder/GovukDateInputSettings.generated.cs
> -		///<summary>
Is removing the readonly property intentional?

2023-12-01 15:43 UTC, HarryAmmon commented on GovUk.Frontend.Umbraco/HtmlGeneration/DateInputHtmlEnhancer.cs
> +            if (wrapperForDayInput != null)
Prefer the `is not` syntax for checking null for the same reason we use `string` not `String`

2023-12-05 09:25 UTC, sussexrick commented
@HarryAmmon Comments addressed, ready for another look

2023-12-05 09:52 UTC, HarryAmmon approved these changes

2023-12-05 11:44 UTC, merged