Feature/custom validator
thepensionsregulator/govuk-frontend-aspnetcore-extensions pull request #62
Opened 2022-09-23 15:37 UTC by bentpr

Number of changes to support custom validation attributes

2022-09-26 10:05 UTC, sussexrick commented
I'd like to see a better error than this in the example app:

![image](https://user-images.githubusercontent.com/1260550/192248026-352c755b-1632-433a-877c-6a9103263217.png)

It's not related to this PR but this page should have the form legend as the h1, like checkboxes do.

![image](https://user-images.githubusercontent.com/1260550/192248958-41fdced1-1f38-46ad-89bc-6b7ffc39df2c.png)

This one is not working:

![image](https://user-images.githubusercontent.com/1260550/192249879-b79b111f-3990-49b1-8f1b-f2ba47ee408e.png)

2022-09-26 10:19 UTC, sussexrick commented
On the text input page on the Umbraco app. I suspect this is the length validator showing the wrong message, because there is a minimum length of 5 characters and a value of `12345` does not display this error but `abcde` does.

![image](https://user-images.githubusercontent.com/1260550/192252541-a738c798-8a1e-4d4e-8dc2-5a3e8841f24b.png)

2022-09-26 10:19 UTC, sussexrick requested changes

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/README.md
> +                options.rules['banana'] = {
could be `options.rules['banana'] = options.params`

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/README.md
> +3. All being well, you should find that the generated html element now has `data-val-banana` and `data-val-banana-additionaparamter` attributes. These correspond to the validation attribute added to
typos in `additionalparameter`

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/Validation/ClientSideValidationHtmlEnhancer.cs
>                      if (validateElement) { targetElement.Attributes.Add("data-val", "true"); }
If `customValidation.AddValidation()` has added `data-val=true` would we end up with a duplicate attribute here?

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/__tests__/govuk-validation-validateCustom.tests.js
> +        );
Not testing that the custom property is passed and set to Banana

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/wwwroot/govuk/govuk-validation.js
> +        var data = {};
No reason to use `var` in JS, always `let` or `const`

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/wwwroot/govuk/govuk-validation.js
> +        /*
This should come out as it's been replaced. We have git history to refer to it.

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.ExampleApp/Models/CustomValidationViewModel.cs
> +    public class CustomValidatorAttribute : ValidationAttribute, IClientModelValidator
I know you had these together for convenient testing, but separate them out for the PR

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.ExampleApp/Views/CustomValidation/Index.cshtml
> +                console.log(value);
These can come out

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.ExampleApp/Views/CustomValidation/Index.cshtml
> +                    options.rules['custom'] = {
Again I think you can condense this to `options.rules['custom'] = options.params`

2022-09-26 10:19 UTC, sussexrick commented on GovUk.Frontend.ExampleApp/Views/CustomValidation/Index.cshtml
> +    <script type="text/javascript">
Include the script as a separate file to show good practice. Implemented apps should ban inline JS using a CSP.

2022-09-30 14:32 UTC, bentpr commented on GovUk.Frontend.AspNetCore.Extensions/Validation/ClientSideValidationHtmlEnhancer.cs
>                      if (validateElement) { targetElement.Attributes.Add("data-val", "true"); }
Don't believe so - I've not seen any duplicates?

2022-10-03 08:56 UTC, sussexrick approved these changes, later dismissed

2022-10-03 08:56 UTC, sussexrick commented on GovUk.Frontend.AspNetCore.Extensions/DataAnnotationsStringLocalizer.cs
> +        //public IStringLocalizer WithCulture(CultureInfo culture)
An old experiment?

2022-10-03 09:10 UTC, sussexrick approved these changes

2022-10-03 09:12 UTC, merged